index:
    path: /
    controller: App\Controller\DefaultController::index
    
book:
    path: /book/{id}
    controller: App\Controller\BookController::showBook

#login:
#    path: /login
#    controller: App\Controller\UserController::login

bookcase:
    path: /bookcase/{id}
    controller: App\Controller\BookcaseController::showBookcase

#user:
#    path: /user/{id}
#    controller: App\Controller\UserController::profile

newBookcase:
    path: /new/bookcase
    controller: App\Controller\BookcaseController::addBookcase

bookcases:
    path: /bookcase
    controller: App\Controller\BookcaseController::showBookcases

newBook:
    path: /new/book
    controller: App\Controller\BookController::addBook
