index:
    path: /
    controller: App\Controller\DefaultController::index
    
book:
    path: /book/{id}
    controller: App\Controller\BookController::showBook

login:
    path: /login
    controller: App\Controller\UserController::login

bookcase:
    path: /bookcase/{id}
    controller: App\Controller\BookcaseController::listBooksFromBookcase

user:
    path: /user/{id}
    controller: App\Controller\UserController::showUserDetails

