index:
    path: /
    controller: App\Controller\DefaultController::index

about:
    path: /about
    controller: App\Controller\DefaultController::about

book:
    path: /book/{id}
    controller: App\Controller\BookController::showBook

books:
    path: /books
    controller: App\Controller\BookController::showBooks

newBook:
    path: /new/book
    controller: App\Controller\BookController::addBook

removeBook:
    path: /remove/book/{id}
    controller: App\Controller\BookController::removeBook

bookcase:
    path: /bookcase/{id}
    controller: App\Controller\BookcaseController::showBookcase

newBookcase:
    path: /new/bookcase
    controller: App\Controller\BookcaseController::addBookcase

bookcases:
    path: /bookcase
    controller: App\Controller\BookcaseController::showBookcases

#login:
#    path: /login
#    controller: App\Controller\UserController::login

#user:
#    path: /user/{id}
#    controller: App\Controller\UserController::profile
